USE empleados;

SELECT ENO,SAL,COMM,DEPTNO,HIREDATE from EMP;

SELECT * from DEPT;

SELECT ENAME,JOB from EMP ORDER BY JOB;

SELECT DISTINCT DEPTNO, JOB from EMP ORDER BY DEPTNO;





SELECT DISTINCT DEPTNO from EMP;

SELECT ENAME,SAL *14 from EMP;

SELECT ENAME, SAL * COMM AS BONO from EMP;

SELECT * from EMP WHERE JOB = "SALESMAN";

SELECT * from EMP WHERE DEPTNO != 30;

SELECT ENAME from EMP WHERE SAL >2000;

SELECT * from EMP WHERE HIREDATE <'1982-01-01';

SELECT ENAME,HIREDATE from EMP WHERE JOB ="ANALYST";

SELECT * from EMP WHERE SAL > (SELECT SAL from EMP WHERE ENAME = "ADAMS");

SELECT * from EMP WHERE DEPTNO = (SELECT DEPTNO from EMP WHERE ENAME= "CLARK");

SELECT * from EMP WHERE MGR =(SELECT ENO from EMP WHERE ENAME ="BLAKE");

SELECT ENAME from EMP WHERE JOB= "SALESMAN" AND SAL >1500;

SELECT * from EMP WHERE COMM IS NOT NULL AND COMM > 0;

SELECT * from EMP WHERE ENAME IN ("SMITH", "ALLEN", "SCOTT");

SELECT * from EMP WHERE ENAME NOT IN ("SMITH", "ALLEN", "SCOTT");

SELECT * from EMP WHERE DEPTNO=(SELECT DEPTNO from DEPT WHERE LOC="CHICAGO");

SELECT * from EMP WHERE DEPTNO=10 OR DEPTNO=20;